name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile and Run Java Program
      run: |
        javac add.java
        java add < input.txt  # Redirect input from the file

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-build
        path: .

    - name: Compile and Run Java Program
      run: |
          javac add.java
          java add < input.txt > output.txt  # Redirect output to a file

    - name: Display Output
      run: cat output.txt  # Display the output for verification

