name: Notify Repo A2

on:
  push:
    branches:
      - main  # Adjust this to match the branch you want to trigger the workflow

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A1
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Trigger Repo A2 Workflow
      run: |
        echo "${{ secrets.REPO_A2_PAT }}" | gh auth login --with-token
        gh api repos/contact-deepak/A2/dispatches \
          -F event_type=trigger \
          -H "Accept: application/vnd.github+json"
